# Generated by Django 3.1 on 2020-09-11 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_fields_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 11, 15, 39, 33, 721390, tzinfo=utc), verbose_name='Date'),
        ),
    ]
